fixed archive adding logic and added package sanity checks

diff --git a/iso-rebuild b/iso-rebuild
--- a/iso-rebuild
+++ b/iso-rebuild
@@ -130,14 +130,9 @@ Must be run as root.
 
    Filesystem Options:
 
-    --add-archive-to-user "USERNAME /path/to/local/archive.tar.gz"
-      Extract the contents of a tar archive to USERNAME's home directory (/home/USERNAME)
-
-    --add-zip-to-user "USERNAME /path/to/local/zipfile.zip"
-      Extract the contents of a zip file to USERNAME's home directory (/home/USERNAME)
-
     --add-archive-to-root "/path/to/local/archive.tar.gz"
       Extract the contents of a tar archive to the root of the filesystem
+        tar -czvf ~/iso-rebuild-test/will.tar.gz /home/whofferbert/{.bashrc,.ssh,.vimrc}
  
     --add-zip-to-root "/path/to/local/zipfile.zip"
       Extract the contents of a zip file to the root of the filesystem
@@ -210,8 +205,7 @@ handle_args () {
   vm-preinstall-script:,vm-postinstall-script:,no-upgrade,
   no-clean-chroot,package-config:,out-dir:,out-vm-iso:,no-out-iso,
   real-quiet,no-dist-upgrde,dont-run-install,casper-name:
-  no-clean-local-fs,add-archive-to-user:,add-zip-to-user:,
-  add-archive-to-root:,add-zip-to-root:"  -- "$@")
+  no-clean-local-fs,add-archive-to-root:,add-zip-to-root:"  -- "$@")
   
   eval set -- "$OPTS"
   while true
@@ -246,8 +240,6 @@ handle_args () {
         --no-clean-local-fs) clean_local_fs="f" ; shift;;
         --dont-run-install) run_install="f" ; shift;;
         --casper-name) casper_username="$2" ; shift 2;;
-        --add-archive-to-user) addtar+=("/home/$2") ; shift 2;;
-        --add-zip-to-user) addzip+=("/home/$2") ; shift 2;;
         --add-archive-to-root) addtar+=("/ $2"); shift 2;;
         --add-zip-to-root) addzip+=("/ $2"); shift 2;;
         --) shift; break;;
@@ -424,6 +416,15 @@ chroot_install () {
         done
       echo -e "\nInstalling $pkg_sanity into chroot environment ... \n"
       eval chroot $chroot apt-get install -y $inst $pkg_sanity $chroot_fd
+      if [ $? -ne 0 ]
+        then
+          echo -e "\nEncountered a problem! Trying packages one at a time ...\n"
+          for pkg in $pkg_sanity
+            do
+              eval chroot $chroot apt-get install -y $inst $pkg $chroot_fd
+              [ $? -ne 0 ] && warn "Unable to install $pkg!"
+            done
+      fi
   fi
 }
 
@@ -452,7 +453,7 @@ chroot_exec () {
 }
 
 add_zips_to_chroot () {
-  for data in "${addzip[*]}"
+  for data in "${addzip[@]}"
     do
       dest=$(echo "$data" | cut -d" " -f1)
       file=$(echo "$data" | cut -d" " -f2-)
@@ -462,7 +463,7 @@ add_zips_to_chroot () {
 }
 
 add_tars_to_chroot () {
-  for data in "${addtar[*]}"
+  for data in "${addtar[@]}"
     do
       dest=$(echo "$data" | cut -d" " -f1)
       file=$(echo "$data" | cut -d" " -f2-)
